# Generated by Django 3.0.5 on 2020-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_start', models.DateField()),
                ('train_end', models.DateField()),
                ('test_start', models.DateField()),
                ('test_end', models.DateField()),
                ('epoch', models.IntegerField()),
                ('batch_size', models.IntegerField()),
            ],
        ),
    ]
