# Generated by Django 3.0.5 on 2020-05-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnn_estimator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodel',
            name='images',
        ),
    ]
