# Generated by Django 3.0.5 on 2020-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnn_estimator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='title',
            field=models.CharField(default='no name', max_length=100),
            preserve_default=False,
        ),
    ]
