# Generated by Django 3.0.5 on 2020-05-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnn_estimator', '0002_remove_learningmodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='images',
            field=models.ImageField(default='null.jpg', upload_to='', verbose_name='学習過程'),
        ),
    ]
