# Generated by Django 3.0.5 on 2020-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnn_estimator', '0003_auto_20200503_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodel',
            name='test_acc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='train_acc',
            field=models.FloatField(default=0.0),
        ),
    ]
