# Generated by Django 3.0.5 on 2020-05-04 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnn_estimator', '0004_auto_20200503_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='model_dev_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
