# Generated by Django 3.0.5 on 2020-05-04 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dnn_estimator', '0005_learningmodel_model_dev_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodel',
            name='batch_size',
            field=models.IntegerField(verbose_name='バッチサイズ'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='epoch',
            field=models.IntegerField(verbose_name='エポック数'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='model_dev_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 6, 57, 58, 99510, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='test_acc',
            field=models.FloatField(default=0.0, verbose_name='テストデータ正答率'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='test_end',
            field=models.DateField(verbose_name='テストデータ終了日'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='test_start',
            field=models.DateField(verbose_name='テストデータ開始日'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='train_acc',
            field=models.FloatField(default=0.0, verbose_name='訓練データ正答率'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='train_end',
            field=models.DateField(verbose_name='訓練データ終了日'),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='train_start',
            field=models.DateField(verbose_name='訓練データ開始日'),
        ),
    ]
