# Generated by Django 3.0.5 on 2020-05-04 06:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dnn_estimator', '0006_auto_20200504_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodel',
            name='model_dev_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 6, 59, 48, 766537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='ユーザ定義モデル名'),
        ),
    ]
